### PR TITLE
fixed js syntax error, unrecognized expression

### PR DESCRIPTION
**Pull request by cnyyk**
Fixed js error:
Syntax error, unrecognized expression: `.home #site-navigation li a[href*=#]`
theme.js line 261, 290.

WordPress Version: 4.5
jQuery Version: 1.12.3

### CODE REVIEW

**Comment by cnyyk** [comment]
WordPress Version: 4.5
jQuery Version: 1.12.3

screen shot 2016-04-14 at 11 11 04 am

**Comment by cnyyk** [comment]
FA icon and text alignment issue:

BEFORE:

screen shot 2016-04-14 at 12 00 23 pm

AFTER:

screen shot 2016-04-14 at 12 00 57 pm

**Comment by KienTrong** [comment]
@cnyyk If you edit something in style.css, you will need to add it to .scss file too because we use SASS to generate style.css.

For this case you will need to add it into : /assets/sass/_sections.scss line 664

Thanks.

**Comment by cnyyk** [comment]
@KienTrong revert the style.css modification and committed the sass file.

**Comment by KienTrong** [comment]
@cnyyk Sorry for the misunderstand, you should add it to both file because when pull request to `master`, the file will be ready for release, we usually working on `development` branch.

This is first time we working with pull request from a person outside of our team. ;)

**Comment by cnyyk** [comment]
@KienTrong It's my great pleasure to participate this awesome theme as a first outsider. Now I revert the revert commit and both 3 files work fine for production and development environment.

**Pull request merged**
