### PR TITLE
fix not working scrolling of navigation links in WP 5.6 (jQuery 3.5)

### PR DESCRIPTION
**Pull request by SeifertDaniel**

### CODE REVIEW

**Comment by lgroleau** [comment]
Thanks so much , you saved my night :)

**Comment by despino** [comment]
@SeifertDaniel Question: how do you get to the .js file if you are only able to access the Wordpress UI for this theme? I'm trying to fix this issue with your solution.

**Comment by d3datadev** [comment]
@despino Without knowledge of your installation, it is difficult to answer the question. 

You only have direct file access with an (S)FTP connection or via SSH. With managed installations, however, you do not always have this. 

Perhaps you can correct the file with a file editor from the backend. Of course, this leads the restriction ad absurdum. 

Ask the author to merge the pull request and hope that the change will soon be available on your system.

**Comment by SeifertDaniel** [comment]
@despino Without knowledge of your installation, it is difficult to answer the question. 

You only have direct file access with an (S)FTP connection or via SSH. With managed installations, however, you do not always have this. 

Perhaps you can correct the file with a file editor from the backend. Of course, this leads the restriction ad absurdum. 

Ask the author to merge the pull request and hope that the change will soon be available on your system.

**Comment by SeifertDaniel** [comment]
Since the bug has already been solved with 7efa4ae outside this PR, no more merging is needed.

**Pull request closed without merging**
